import stylistic from '@stylistic/eslint-plugin';

const content = {
    files: ['src/content/**/*.{js,cjs,mjs,jsx}'],
    languageOptions: {
        parserOptions: { ecmaFeatures: { jsx: true } },
    },
    plugins: { '@stylistic': stylistic },
    rules: {
        '@stylistic/array-bracket-newline': ['error', 'consistent'],
        '@stylistic/array-bracket-spacing': 'error',
        '@stylistic/arrow-parens': ['error', 'as-needed'],
        '@stylistic/arrow-spacing': 'error',
        '@stylistic/block-spacing': 'error',
        '@stylistic/comma-dangle': ['error', 'always-multiline'],
        '@stylistic/comma-spacing': 'error',
        '@stylistic/comma-style': 'error',
        '@stylistic/computed-property-spacing': 'error',
        '@stylistic/curly-newline': 'error',
        '@stylistic/dot-location': ['error', 'property'],
        '@stylistic/eol-last': 'error',
        '@stylistic/function-call-argument-newline': ['error', 'consistent'],
        '@stylistic/function-call-spacing': 'error',
        '@stylistic/generator-star-spacing': ['error', { after: true, before: false }],
        '@stylistic/indent': 'error',
        '@stylistic/jsx-child-element-spacing': 'error',
        '@stylistic/jsx-closing-bracket-location': 'error',
        '@stylistic/jsx-closing-tag-location': ['error', 'line-aligned'],
        '@stylistic/jsx-curly-brace-presence': ['error', { propElementValues: 'always' }],
        '@stylistic/jsx-curly-spacing': 'error',
        '@stylistic/jsx-equals-spacing': 'error',
        '@stylistic/jsx-first-prop-new-line': 'error',
        '@stylistic/jsx-function-call-newline': 'error',
        '@stylistic/jsx-indent-props': 'error',
        '@stylistic/jsx-max-props-per-line': ['error', { when: 'multiline' }],
        '@stylistic/jsx-pascal-case': ['error', { allowAllCaps: true }],
        '@stylistic/jsx-quotes': 'error',
        '@stylistic/jsx-self-closing-comp': 'error',
        '@stylistic/jsx-tag-spacing': ['error', { beforeClosing: 'never' }],
        '@stylistic/key-spacing': 'error',
        '@stylistic/keyword-spacing': 'error',
        '@stylistic/line-comment-position': 'error',
        '@stylistic/linebreak-style': 'error',
        '@stylistic/max-len': ['error', { code: 80 }],
        '@stylistic/multiline-comment-style': 'error',
        '@stylistic/no-extra-parens': ['error', 'functions'],
        '@stylistic/no-extra-semi': 'error',
        '@stylistic/no-mixed-spaces-and-tabs': 'error',
        '@stylistic/no-multi-spaces': 'error',
        '@stylistic/no-tabs': 'error',
        '@stylistic/no-trailing-spaces': 'error',
        '@stylistic/no-whitespace-before-property': 'error',
        '@stylistic/nonblock-statement-body-position': 'error',
        '@stylistic/object-curly-newline': 'error',
        '@stylistic/object-curly-spacing': ['error', 'always'],
        '@stylistic/operator-linebreak': ['error', 'before'],
        '@stylistic/padded-blocks': ['error', 'never'],
        '@stylistic/padding-line-between-statements': 'error',
        '@stylistic/quote-props': ['error', 'consistent-as-needed'],
        '@stylistic/quotes': ['error', 'single'],
        '@stylistic/rest-spread-spacing': 'error',
        '@stylistic/semi': 'error',
        '@stylistic/semi-spacing': 'error',
        '@stylistic/semi-style': 'error',
        '@stylistic/space-before-blocks': 'error',
        '@stylistic/space-before-function-paren': ['error', { named: 'never' }],
        '@stylistic/space-in-parens': 'error',
        '@stylistic/space-infix-ops': 'error',
        '@stylistic/space-unary-ops': 'error',
        '@stylistic/spaced-comment': 'error',
        '@stylistic/switch-colon-spacing': 'error',
        '@stylistic/template-curly-spacing': 'error',
        '@stylistic/template-tag-spacing': 'error',
        '@stylistic/wrap-iife': 'error',
        '@stylistic/yield-star-spacing': 'error',
        'accessor-pairs': 'error',
        'array-callback-return': 'error',
        'arrow-body-style': 'error',
        'block-scoped-var': 'error',
        'capitalized-comments': 'error',
        'complexity': ['error', { max: 32 }],
        'constructor-super': 'error',
        'curly': ['error', 'multi-line'],
        'default-case-last': 'error',
        'default-param-last': 'error',
        'dot-notation': 'error',
        'for-direction': 'error',
        'func-name-matching': 'error',
        'func-names': ['error', 'never', { generators: 'always' }],
        'func-style': ['error', 'declaration', { allowArrowFunctions: true }],
        'getter-return': 'error',
        'grouped-accessor-pairs': 'error',
        'logical-assignment-operators': 'error',
        'max-lines': 'error',
        'max-lines-per-function': ['error', { max: 80 }],
        'max-nested-callbacks': 'error',
        'new-cap': ['error', { properties: false }],
        'no-array-constructor': 'error',
        'no-async-promise-executor': 'error',
        'no-case-declarations': 'error',
        'no-class-assign': 'error',
        'no-compare-neg-zero': 'error',
        'no-console': 'error',
        'no-const-assign': 'error',
        'no-constant-binary-expression': 'error',
        'no-constructor-return': 'error',
        'no-control-regex': 'error',
        'no-debugger': 'error',
        'no-delete-var': 'error',
        'no-div-regex': 'error',
        'no-dupe-args': 'error',
        'no-dupe-class-members': 'error',
        'no-dupe-else-if': 'error',
        'no-dupe-keys': 'error',
        'no-duplicate-case': 'error',
        'no-duplicate-imports': 'error',
        'no-else-return': 'error',
        'no-empty-character-class': 'error',
        'no-empty-function': 'error',
        'no-empty-pattern': 'error',
        'no-empty-static-block': 'error',
        'no-eq-null': 'error',
        'no-ex-assign': 'error',
        'no-extra-bind': 'error',
        'no-extra-boolean-cast': 'error',
        'no-extra-label': 'error',
        'no-fallthrough': 'error',
        'no-func-assign': 'error',
        'no-global-assign': 'error',
        'no-implied-eval': 'error',
        'no-import-assign': 'error',
        'no-inline-comments': 'error',
        'no-inner-declarations': 'error',
        'no-invalid-regexp': 'error',
        'no-irregular-whitespace': 'error',
        'no-label-var': 'error',
        'no-lone-blocks': 'error',
        'no-loss-of-precision': 'error',
        'no-misleading-character-class': 'error',
        'no-multi-str': 'error',
        'no-new': 'error',
        'no-new-native-nonconstructor': 'error',
        'no-new-wrappers': 'error',
        'no-obj-calls': 'error',
        'no-object-constructor': 'error',
        'no-octal': 'error',
        'no-prototype-builtins': 'error',
        'no-redeclare': 'error',
        'no-regex-spaces': 'error',
        'no-self-assign': 'error',
        'no-self-compare': 'error',
        'no-setter-return': 'error',
        'no-shadow-restricted-names': 'error',
        'no-template-curly-in-string': 'error',
        'no-this-before-super': 'error',
        'no-unassigned-vars': 'error',
        'no-undef-init': 'error',
        'no-underscore-dangle': 'error',
        'no-unexpected-multiline': 'error',
        'no-unneeded-ternary': 'error',
        'no-unreachable': 'error',
        'no-unsafe-finally': 'error',
        'no-unsafe-negation': 'error',
        'no-unsafe-optional-chaining': 'error',
        'no-unused-labels': 'error',
        'no-unused-private-class-members': 'error',
        'no-useless-assignment': 'error',
        'no-useless-backreference': 'error',
        'no-useless-call': 'error',
        'no-useless-catch': 'error',
        'no-useless-computed-key': 'error',
        'no-useless-concat': 'error',
        'no-useless-constructor': 'error',
        'no-useless-escape': 'error',
        'no-useless-rename': 'error',
        'no-useless-return': 'error',
        'no-var': 'error',
        'no-void': ['error', { allowAsStatement: true }],
        'no-warning-comments': 'error',
        'object-shorthand': 'error',
        'operator-assignment': 'error',
        'prefer-arrow-callback': 'error',
        'prefer-destructuring': ['error', { array: false }],
        'prefer-numeric-literals': 'error',
        'prefer-object-has-own': 'error',
        'prefer-object-spread': 'error',
        'prefer-promise-reject-errors': 'error',
        'prefer-regex-literals': 'error',
        'prefer-spread': 'error',
        'preserve-caught-error': 'error',
        'require-atomic-updates': 'error',
        'require-await': 'error',
        'require-yield': 'error',
        'sort-imports': ['error', { allowSeparatedGroups: true }],
        'symbol-description': 'error',
        'use-isnan': 'error',
        'valid-typeof': 'error',
    },
};

const jsxOverride = {
    files: ['src/content/**/front-end/*.jsx'],
    rules: { '@stylistic/comma-dangle': 'off' },
};

const maxLenOverride = {
    files: [
        'src/content/data-structures/MaxHeap.js',
        'src/content/data-structures/MinHeap.js',
        'src/content/data-structures/PriorityQueue.js',
        'src/content/easy/2001-3000/2383.js',
        'src/content/easy/3001-4000/3633.js',
        'src/content/medium/1001-2000/1292.js',
        'src/content/medium/1001-2000/1334.js',
        'src/content/medium/1001-2000/1343.js',
        'src/content/medium/1001-2000/1430.mjs',
        'src/content/medium/1001-2000/1438.js',
        'src/content/medium/1001-2000/1577.js',
        'src/content/medium/2001-3000/2512.js',
        'src/content/medium/3001-4000/3635.js',
    ],
    rules: { '@stylistic/max-len': ['error', { code: 90 }] },
};

const precisionOverride = {
    files: ['src/content/medium/2001-3000/2847.mjs'],
    rules: { 'no-loss-of-precision': 'off' },
};

export default [
    content,
    jsxOverride,
    maxLenOverride,
    precisionOverride,
];
